import type {
  FurnitureBrand,
  FurnitureCategory,
  FurnitureModel,
  MaterialItem,
  MaterialType,
} from "../types/designIntelligence";

// ─── Material Library (66 materials) ─────────────────────────────────────────

export const MATERIALS: MaterialItem[] = [
  // WOOD (12)
  {
    id: "mat-001",
    name: "White Oak Natural",
    materialType: "Wood",
    colorName: "Natural Oak",
    colorHex: "#C8A96E",
    finish: "Matte",
    priceSqFt: 18,
    csiCode: "06 40 00",
    leadTimeWeeks: 4,
    sustainability: "FSC Certified",
    description:
      "Straight-grain white oak with a natural matte finish, warm and neutral.",
  },
  {
    id: "mat-002",
    name: "Walnut Oiled",
    materialType: "Wood",
    colorName: "Dark Walnut",
    colorHex: "#5C3A1E",
    finish: "Oiled",
    priceSqFt: 24,
    csiCode: "06 40 00",
    leadTimeWeeks: 4,
    sustainability: "FSC Certified",
    description: "Rich dark walnut with hand-rubbed oil finish, premium feel.",
  },
  {
    id: "mat-003",
    name: "Maple Clear",
    materialType: "Wood",
    colorName: "Light Maple",
    colorHex: "#E8D5B0",
    finish: "Clear Lacquer",
    priceSqFt: 16,
    csiCode: "06 40 00",
    leadTimeWeeks: 3,
    description: "Hard maple with clear coat, ideal for high-traffic surfaces.",
  },
  {
    id: "mat-004",
    name: "Ash Bleached",
    materialType: "Wood",
    colorName: "Bleached Ash",
    colorHex: "#DDD3C0",
    finish: "Matte",
    priceSqFt: 20,
    csiCode: "06 40 00",
    leadTimeWeeks: 4,
    description: "Bleached ash for a Scandinavian aesthetic.",
  },
  {
    id: "mat-005",
    name: "Ebonized Oak",
    materialType: "Wood",
    colorName: "Ebony",
    colorHex: "#1A1008",
    finish: "Satin",
    priceSqFt: 22,
    csiCode: "06 40 00",
    leadTimeWeeks: 5,
    description: "Deep ebonized finish for dramatic, high-contrast spaces.",
  },
  {
    id: "mat-006",
    name: "Bamboo Carbonized",
    materialType: "Wood",
    colorName: "Caramel",
    colorHex: "#A0703A",
    finish: "Satin",
    priceSqFt: 14,
    csiCode: "06 40 00",
    leadTimeWeeks: 3,
    sustainability: "Rapidly Renewable",
    description: "Sustainable bamboo with carbonized amber tone.",
  },
  {
    id: "mat-007",
    name: "Cherry Aged",
    materialType: "Wood",
    colorName: "Aged Cherry",
    colorHex: "#8B3A2A",
    finish: "Semi-Gloss",
    priceSqFt: 21,
    csiCode: "06 40 00",
    leadTimeWeeks: 5,
    description: "Traditional cherry with warm reddish-brown character.",
  },
  {
    id: "mat-008",
    name: "Teak Reclaimed",
    materialType: "Wood",
    colorName: "Teak Gold",
    colorHex: "#9B7D4A",
    finish: "Oiled",
    priceSqFt: 30,
    csiCode: "06 40 00",
    leadTimeWeeks: 6,
    sustainability: "Reclaimed",
    description: "Reclaimed teak with authentic grain variation.",
  },
  {
    id: "mat-009",
    name: "Pine Whitewashed",
    materialType: "Wood",
    colorName: "Whitewash",
    colorHex: "#EDE8DE",
    finish: "Whitewash",
    priceSqFt: 12,
    csiCode: "06 40 00",
    leadTimeWeeks: 2,
    description: "Coastal-style whitewash over natural pine grain.",
  },
  {
    id: "mat-010",
    name: "Rift-Cut Oak Stained",
    materialType: "Wood",
    colorName: "Graphite Oak",
    colorHex: "#6B6B6B",
    finish: "Matte",
    priceSqFt: 26,
    csiCode: "06 40 00",
    leadTimeWeeks: 5,
    description:
      "Rift-cut white oak with graphite stain, contemporary hospitality staple.",
  },
  {
    id: "mat-011",
    name: "Zebrawood Natural",
    materialType: "Wood",
    colorName: "Zebrawood",
    colorHex: "#B8933F",
    finish: "Clear",
    priceSqFt: 32,
    csiCode: "06 40 00",
    leadTimeWeeks: 6,
    description:
      "Exotic zebrawood with distinctive grain pattern for accent panels.",
  },
  {
    id: "mat-012",
    name: "Birch Ply Baltic",
    materialType: "Wood",
    colorName: "Baltic Birch",
    colorHex: "#E2C98A",
    finish: "Unfinished",
    priceSqFt: 10,
    csiCode: "06 18 23",
    leadTimeWeeks: 2,
    description: "Void-free Baltic birch for millwork and case goods.",
  },
  // METAL (10)
  {
    id: "mat-013",
    name: "Brushed Steel",
    materialType: "Metal",
    colorName: "Satin Steel",
    colorHex: "#B8BEC7",
    finish: "Brushed",
    priceSqFt: 28,
    csiCode: "05 12 00",
    leadTimeWeeks: 4,
    description: "Grade 304 stainless steel with directional brushed finish.",
  },
  {
    id: "mat-014",
    name: "Powder Matte Black",
    materialType: "Metal",
    colorName: "Matte Black",
    colorHex: "#1C1C1C",
    finish: "Powder Coat",
    priceSqFt: 18,
    csiCode: "05 12 00",
    leadTimeWeeks: 3,
    description: "Textured matte black powder coat on cold-rolled steel.",
  },
  {
    id: "mat-015",
    name: "Antique Brass",
    materialType: "Metal",
    colorName: "Aged Brass",
    colorHex: "#B5943C",
    finish: "Antiqued",
    priceSqFt: 42,
    csiCode: "05 12 00",
    leadTimeWeeks: 5,
    description:
      "Antique brass with living finish that develops character over time.",
  },
  {
    id: "mat-016",
    name: "Raw Blackened Steel",
    materialType: "Metal",
    colorName: "Blackened Steel",
    colorHex: "#2A2520",
    finish: "Raw",
    priceSqFt: 24,
    csiCode: "05 12 00",
    leadTimeWeeks: 4,
    description:
      "Hot-rolled steel with blackening treatment, industrial character.",
  },
  {
    id: "mat-017",
    name: "Polished Chrome",
    materialType: "Metal",
    colorName: "Chrome",
    colorHex: "#D4D8DC",
    finish: "Polished",
    priceSqFt: 35,
    csiCode: "05 12 00",
    leadTimeWeeks: 4,
    description: "Mirror-finish chrome for hardware and accent applications.",
  },
  {
    id: "mat-018",
    name: "Patinated Copper",
    materialType: "Metal",
    colorName: "Verde Copper",
    colorHex: "#7FA88C",
    finish: "Patinated",
    priceSqFt: 52,
    csiCode: "05 12 00",
    leadTimeWeeks: 6,
    description: "Live patina copper evolving naturally over time.",
  },
  {
    id: "mat-019",
    name: "White Powder Coat",
    materialType: "Metal",
    colorName: "Warm White",
    colorHex: "#F5F2EC",
    finish: "Powder Coat",
    priceSqFt: 16,
    csiCode: "05 12 00",
    leadTimeWeeks: 3,
    description: "Clean warm white powder coat for frames and bases.",
  },
  {
    id: "mat-020",
    name: "Brushed Bronze",
    materialType: "Metal",
    colorName: "Oil-Rubbed Bronze",
    colorHex: "#6B4F36",
    finish: "Brushed",
    priceSqFt: 46,
    csiCode: "05 12 00",
    leadTimeWeeks: 5,
    description: "Warm bronze with brushed texture for architectural accents.",
  },
  {
    id: "mat-021",
    name: "Galvanized",
    materialType: "Metal",
    colorName: "Galvanized",
    colorHex: "#ACACAC",
    finish: "Galvanized",
    priceSqFt: 14,
    csiCode: "05 12 00",
    leadTimeWeeks: 2,
    description:
      "Industrial-grade galvanized steel for utilitarian applications.",
  },
  {
    id: "mat-022",
    name: "Copper Sheet",
    materialType: "Metal",
    colorName: "Bright Copper",
    colorHex: "#B87333",
    finish: "Polished",
    priceSqFt: 48,
    csiCode: "05 12 00",
    leadTimeWeeks: 6,
    description: "Pure copper sheet for decorative panels and inlays.",
  },
  // TEXTILE (14)
  {
    id: "mat-023",
    name: "Boucle Ivory",
    materialType: "Textile",
    colorName: "Ivory",
    colorHex: "#F5F0E3",
    finish: "Woven",
    priceSqFt: 22,
    csiCode: "12 05 00",
    leadTimeWeeks: 5,
    sustainability: "OEKO-TEX",
    description:
      "Chunky boucle weave in warm ivory, tactile luxury seating fabric.",
  },
  {
    id: "mat-024",
    name: "Velvet Navy",
    materialType: "Textile",
    colorName: "Deep Navy",
    colorHex: "#1B2A4A",
    finish: "Cut Pile",
    priceSqFt: 26,
    csiCode: "12 05 00",
    leadTimeWeeks: 4,
    description: "Performance velvet in deep navy, COM-available.",
  },
  {
    id: "mat-025",
    name: "Tweed Charcoal",
    materialType: "Textile",
    colorName: "Charcoal",
    colorHex: "#4A4A4A",
    finish: "Woven",
    priceSqFt: 20,
    csiCode: "12 05 00",
    leadTimeWeeks: 4,
    description: "Classic tweed in charcoal with flecked texture.",
  },
  {
    id: "mat-026",
    name: "Linen Natural",
    materialType: "Textile",
    colorName: "Natural Linen",
    colorHex: "#D4C5A9",
    finish: "Plain Weave",
    priceSqFt: 18,
    csiCode: "12 05 00",
    leadTimeWeeks: 3,
    sustainability: "Natural Fiber",
    description: "Undyed linen for casual, organic interior palettes.",
  },
  {
    id: "mat-027",
    name: "Performance Wool Sage",
    materialType: "Textile",
    colorName: "Sage",
    colorHex: "#8A9E89",
    finish: "Woven",
    priceSqFt: 28,
    csiCode: "12 05 00",
    leadTimeWeeks: 5,
    description: "Contract-grade wool with high durability for hospitality.",
  },
  {
    id: "mat-028",
    name: "Mesh Breathable",
    materialType: "Textile",
    colorName: "Medium Grey",
    colorHex: "#9A9EA4",
    finish: "Knit",
    priceSqFt: 15,
    csiCode: "12 05 00",
    leadTimeWeeks: 3,
    description: "Ergonomic mesh back material for task seating.",
  },
  {
    id: "mat-029",
    name: "Mohair Emerald",
    materialType: "Textile",
    colorName: "Emerald",
    colorHex: "#2E7D5E",
    finish: "Cut Pile",
    priceSqFt: 38,
    csiCode: "12 05 00",
    leadTimeWeeks: 6,
    description: "Luxurious mohair in jewel-tone emerald for statement pieces.",
  },
  {
    id: "mat-030",
    name: "Crypton Taupe",
    materialType: "Textile",
    colorName: "Warm Taupe",
    colorHex: "#B0A090",
    finish: "Woven",
    priceSqFt: 24,
    csiCode: "12 05 00",
    leadTimeWeeks: 4,
    description: "Crypton performance fabric, stain and moisture resistant.",
  },
  {
    id: "mat-031",
    name: "Herringbone Cream",
    materialType: "Textile",
    colorName: "Cream",
    colorHex: "#EEE8D5",
    finish: "Woven",
    priceSqFt: 21,
    csiCode: "12 05 00",
    leadTimeWeeks: 4,
    description: "Classic herringbone for upholstery and drapery.",
  },
  {
    id: "mat-032",
    name: "Outdoor Acrylic Terracotta",
    materialType: "Textile",
    colorName: "Terracotta",
    colorHex: "#C0604A",
    finish: "Solution Dyed",
    priceSqFt: 20,
    csiCode: "12 05 00",
    leadTimeWeeks: 3,
    description: "UV-stable solution-dyed acrylic for outdoor furniture.",
  },
  {
    id: "mat-033",
    name: "Acoustic Panel Charcoal",
    materialType: "Acoustic",
    colorName: "Charcoal",
    colorHex: "#3A3A3A",
    finish: "Wrapped",
    priceSqFt: 32,
    csiCode: "09 84 00",
    leadTimeWeeks: 5,
    description: "Fabric-wrapped acoustic panel substrate, NRC 0.85+.",
  },
  {
    id: "mat-034",
    name: "Sheepskin Ivory",
    materialType: "Textile",
    colorName: "Ivory",
    colorHex: "#F0EAD6",
    finish: "Natural",
    priceSqFt: 60,
    csiCode: "12 05 00",
    leadTimeWeeks: 8,
    description:
      "Genuine sheepskin throw for accent seating, hospitality grade.",
  },
  {
    id: "mat-035",
    name: "Basket Weave Stone",
    materialType: "Textile",
    colorName: "Stone",
    colorHex: "#C4BBAA",
    finish: "Woven",
    priceSqFt: 22,
    csiCode: "12 05 00",
    leadTimeWeeks: 4,
    description: "Textured basket weave with warm stone tones.",
  },
  {
    id: "mat-036",
    name: "Jacquard Geometric",
    materialType: "Textile",
    colorName: "Multi-Tone",
    colorHex: "#8A7B6C",
    finish: "Jacquard",
    priceSqFt: 30,
    csiCode: "12 05 00",
    leadTimeWeeks: 6,
    description: "Woven geometric jacquard for accent chairs and headboards.",
  },
  // LEATHER (6)
  {
    id: "mat-037",
    name: "Full Grain Cognac",
    materialType: "Leather",
    colorName: "Cognac",
    colorHex: "#A0622A",
    finish: "Natural",
    priceSqFt: 48,
    csiCode: "12 05 00",
    leadTimeWeeks: 6,
    description: "Full-grain cattle hide in classic cognac, develops patina.",
  },
  {
    id: "mat-038",
    name: "Aniline Black",
    materialType: "Leather",
    colorName: "Jet Black",
    colorHex: "#0D0D0D",
    finish: "Aniline",
    priceSqFt: 54,
    csiCode: "12 05 00",
    leadTimeWeeks: 6,
    description: "Aniline-dyed top-grain leather in jet black, premium feel.",
  },
  {
    id: "mat-039",
    name: "Nubuck Smoke",
    materialType: "Leather",
    colorName: "Smoke Grey",
    colorHex: "#7A7A7A",
    finish: "Nubuck",
    priceSqFt: 58,
    csiCode: "12 05 00",
    leadTimeWeeks: 8,
    description: "Buffed nubuck for a velvety matte surface in neutral grey.",
  },
  {
    id: "mat-040",
    name: "Vinyl Contract Cream",
    materialType: "Leather",
    colorName: "Cream",
    colorHex: "#F0E8D6",
    finish: "Embossed",
    priceSqFt: 16,
    csiCode: "12 05 00",
    leadTimeWeeks: 2,
    description:
      "Contract-grade vinyl with leather texture for high-use applications.",
  },
  {
    id: "mat-041",
    name: "Saddle Tan",
    materialType: "Leather",
    colorName: "Saddle",
    colorHex: "#8B5E3C",
    finish: "Natural",
    priceSqFt: 46,
    csiCode: "12 05 00",
    leadTimeWeeks: 6,
    description: "Classic saddle tan natural leather with western character.",
  },
  {
    id: "mat-042",
    name: "Recycled Leather Slate",
    materialType: "Leather",
    colorName: "Slate",
    colorHex: "#6B7280",
    finish: "Pressed",
    priceSqFt: 22,
    csiCode: "12 05 00",
    leadTimeWeeks: 3,
    sustainability: "Recycled",
    description:
      "Pressed recycled leather composite in slate grey, eco-certified.",
  },
  // STONE & CONCRETE (8)
  {
    id: "mat-043",
    name: "Calacatta Marble",
    materialType: "Stone",
    colorName: "Calacatta",
    colorHex: "#F5F0E8",
    finish: "Honed",
    priceSqFt: 85,
    csiCode: "04 42 00",
    leadTimeWeeks: 8,
    description: "Premium Italian marble with bold gold veining.",
  },
  {
    id: "mat-044",
    name: "Nero Marquina",
    materialType: "Stone",
    colorName: "Black Marble",
    colorHex: "#1A1A1A",
    finish: "Polished",
    priceSqFt: 90,
    csiCode: "04 42 00",
    leadTimeWeeks: 8,
    description:
      "Black Spanish marble with white veining for dramatic surfaces.",
  },
  {
    id: "mat-045",
    name: "Travertine Silver",
    materialType: "Stone",
    colorName: "Silver Travertine",
    colorHex: "#C8C0B4",
    finish: "Filled & Honed",
    priceSqFt: 42,
    csiCode: "04 42 00",
    leadTimeWeeks: 6,
    description: "Classic travertine with silver tone, filled and honed.",
  },
  {
    id: "mat-046",
    name: "Quartz White Carrera",
    materialType: "Stone",
    colorName: "White",
    colorHex: "#EEECE8",
    finish: "Polished",
    priceSqFt: 52,
    csiCode: "04 42 00",
    leadTimeWeeks: 4,
    description:
      "Engineered quartz with Carrera marble aesthetic, low maintenance.",
  },
  {
    id: "mat-047",
    name: "Concrete Acid Wash",
    materialType: "Concrete",
    colorName: "Acid Wash Grey",
    colorHex: "#9A9A98",
    finish: "Acid Washed",
    priceSqFt: 22,
    csiCode: "03 35 00",
    leadTimeWeeks: 3,
    description: "Acid-washed concrete surface with industrial character.",
  },
  {
    id: "mat-048",
    name: "Polished Concrete Light",
    materialType: "Concrete",
    colorName: "Light Grey",
    colorHex: "#C8C8C4",
    finish: "Polished",
    priceSqFt: 18,
    csiCode: "03 35 00",
    leadTimeWeeks: 3,
    description:
      "Light polished concrete for flooring and countertop applications.",
  },
  {
    id: "mat-049",
    name: "GFRC Panel Charcoal",
    materialType: "Concrete",
    colorName: "Charcoal",
    colorHex: "#4A4A48",
    finish: "Sand-Cast",
    priceSqFt: 36,
    csiCode: "03 49 00",
    leadTimeWeeks: 5,
    description: "Glass fiber reinforced concrete panels for wall cladding.",
  },
  {
    id: "mat-050",
    name: "Limestone Buff",
    materialType: "Stone",
    colorName: "Buff",
    colorHex: "#D4C49A",
    finish: "Bush-Hammered",
    priceSqFt: 48,
    csiCode: "04 42 00",
    leadTimeWeeks: 7,
    description:
      "Bush-hammered limestone with warm buff tone for exterior-inspired interiors.",
  },
  // GLASS (6)
  {
    id: "mat-051",
    name: "Frosted Tempered",
    materialType: "Glass",
    colorName: "Frost",
    colorHex: "#E8EDF0",
    finish: "Frosted",
    priceSqFt: 32,
    csiCode: "08 81 00",
    leadTimeWeeks: 4,
    description: "Frosted safety glass for partitions and cabinet inserts.",
  },
  {
    id: "mat-052",
    name: "Smoked Grey Glass",
    materialType: "Glass",
    colorName: "Smoke",
    colorHex: "#8A9098",
    finish: "Tinted",
    priceSqFt: 28,
    csiCode: "08 81 00",
    leadTimeWeeks: 4,
    description: "Smoked grey tinted glass, 30% light transmission.",
  },
  {
    id: "mat-053",
    name: "Low-Iron Clear",
    materialType: "Glass",
    colorName: "Ultra Clear",
    colorHex: "#EDF5F8",
    finish: "Polished",
    priceSqFt: 35,
    csiCode: "08 81 00",
    leadTimeWeeks: 5,
    description: "Low-iron glass for true-color display cases and shelving.",
  },
  {
    id: "mat-054",
    name: "Back-Painted White",
    materialType: "Glass",
    colorName: "White",
    colorHex: "#FAFAFA",
    finish: "Back-Painted",
    priceSqFt: 30,
    csiCode: "08 81 00",
    leadTimeWeeks: 4,
    description:
      "Back-painted glass panel for whiteboard and architectural surfaces.",
  },
  {
    id: "mat-055",
    name: "Seedy Antique Glass",
    materialType: "Glass",
    colorName: "Antique",
    colorHex: "#DDE8D4",
    finish: "Antique",
    priceSqFt: 44,
    csiCode: "08 81 00",
    leadTimeWeeks: 6,
    description:
      "Reproduction antique glass with bubbles and slight distortion.",
  },
  {
    id: "mat-056",
    name: "Wire Glass Safety",
    materialType: "Glass",
    colorName: "Clear Wire",
    colorHex: "#D8E0E8",
    finish: "Wired",
    priceSqFt: 26,
    csiCode: "08 81 00",
    leadTimeWeeks: 3,
    description:
      "Wire-reinforced safety glass for fire-rated partition applications.",
  },
  // LAMINATE & VINYL (8)
  {
    id: "mat-057",
    name: "HPL White Gloss",
    materialType: "Laminate",
    colorName: "High Gloss White",
    colorHex: "#F5F5F5",
    finish: "High Gloss",
    priceSqFt: 8,
    csiCode: "06 58 00",
    leadTimeWeeks: 2,
    description: "High-pressure laminate in gloss white for modern case goods.",
  },
  {
    id: "mat-058",
    name: "Wilsonart Crema Marfil",
    materialType: "Laminate",
    colorName: "Crema Marfil",
    colorHex: "#E8D8B0",
    finish: "Satin",
    priceSqFt: 9,
    csiCode: "06 58 00",
    leadTimeWeeks: 2,
    description:
      "Wilsonart stone pattern laminate, stone aesthetic at laminate price.",
  },
  {
    id: "mat-059",
    name: "Formica Graphite",
    materialType: "Laminate",
    colorName: "Graphite",
    colorHex: "#5A5A5A",
    finish: "Matte",
    priceSqFt: 8,
    csiCode: "06 58 00",
    leadTimeWeeks: 1,
    description: "Formica graphite matte for worksurfaces and panel systems.",
  },
  {
    id: "mat-060",
    name: "LVT Oak Plank",
    materialType: "Vinyl",
    colorName: "Honey Oak",
    colorHex: "#C0943C",
    finish: "Embossed",
    priceSqFt: 6,
    csiCode: "09 65 19",
    leadTimeWeeks: 2,
    description:
      "Luxury vinyl tile with wood-look oak plank pattern, waterproof.",
  },
  {
    id: "mat-061",
    name: "LVT Concrete Grey",
    materialType: "Vinyl",
    colorName: "Concrete",
    colorHex: "#B0B0B0",
    finish: "Matte",
    priceSqFt: 6,
    csiCode: "09 65 19",
    leadTimeWeeks: 2,
    description: "Concrete-look LVT for high-traffic commercial applications.",
  },
  {
    id: "mat-062",
    name: "Carpet Tile Heathered",
    materialType: "Textile",
    colorName: "Heathered Grey",
    colorHex: "#8A8E94",
    finish: "Loop Pile",
    priceSqFt: 7,
    csiCode: "09 68 16",
    leadTimeWeeks: 3,
    description:
      "Modular carpet tile with heathered pattern, recyclable backing.",
  },
  {
    id: "mat-063",
    name: "Cork Natural",
    materialType: "Composite",
    colorName: "Natural Cork",
    colorHex: "#BFA882",
    finish: "Waxed",
    priceSqFt: 12,
    csiCode: "09 65 16",
    leadTimeWeeks: 3,
    sustainability: "Renewable",
    description: "Natural cork flooring with wax finish, acoustic and thermal.",
  },
  {
    id: "mat-064",
    name: "Rubber Charcoal",
    materialType: "Composite",
    colorName: "Charcoal",
    colorHex: "#3A3A3A",
    finish: "Studded",
    priceSqFt: 10,
    csiCode: "09 65 29",
    leadTimeWeeks: 2,
    description:
      "Studded rubber tile for gym, back-of-house, and utility zones.",
  },
  // COMPOSITE & SPECIALTY (2 extra)
  {
    id: "mat-065",
    name: "Corian Glacier White",
    materialType: "Composite",
    colorName: "Glacier White",
    colorHex: "#F2F4F6",
    finish: "Matte",
    priceSqFt: 38,
    csiCode: "06 65 00",
    leadTimeWeeks: 4,
    description: "Corian solid surface in glacier white, seamless fabrication.",
  },
  {
    id: "mat-066",
    name: "Richlite Dark Roast",
    materialType: "Composite",
    colorName: "Dark Roast",
    colorHex: "#3A2E22",
    finish: "Smooth",
    priceSqFt: 44,
    csiCode: "06 65 00",
    leadTimeWeeks: 5,
    sustainability: "Recycled Paper",
    description: "Recycled-paper composite in espresso tone, heat resistant.",
  },
];

// ─── Furniture Model Library (100+ models) ───────────────────────────────────

const HM: FurnitureBrand = "Herman Miller";
const KN: FurnitureBrand = "Knoll";
const SC: FurnitureBrand = "Steelcase";
const HW: FurnitureBrand = "Haworth";
const HS: FurnitureBrand = "Humanscale";
const VT: FurnitureBrand = "Vitra";
const RH: FurnitureBrand = "Restoration Hardware";
const WE: FurnitureBrand = "West Elm Contract";
const KB: FurnitureBrand = "Kimball";
const TK: FurnitureBrand = "Teknion";

export const FURNITURE_MODELS: FurnitureModel[] = [
  // ── TASK SEATING (15) ─────────────────────────────────────────────────────
  {
    id: "fm-001",
    name: "Aeron Chair",
    brand: HM,
    category: "Seating",
    style: ["Modern", "Contemporary"],
    dimensions: { widthIn: 27, depthIn: 17, heightIn: 42, weightLbs: 40 },
    priceRangeLow: 1400,
    priceRangeHigh: 1800,
    availableMaterials: [MATERIALS[27]],
    csiCode: "12 51 13",
    leadTimeWeeks: 4,
    sustainabilityCert: "GREENGUARD Gold",
    description:
      "Iconic ergonomic task chair with PostureFit SL lumbar support, 8Z Pellicle mesh.",
    thumbnailColor: "oklch(0.4 0.04 240)",
    tags: ["ergonomic", "task", "office", "bestseller"],
  },
  {
    id: "fm-002",
    name: "Embody Chair",
    brand: HM,
    category: "Seating",
    style: ["Modern", "Contemporary"],
    dimensions: { widthIn: 29, depthIn: 18, heightIn: 43, weightLbs: 43 },
    priceRangeLow: 1800,
    priceRangeHigh: 2400,
    availableMaterials: [MATERIALS[26]],
    csiCode: "12 51 13",
    leadTimeWeeks: 5,
    sustainabilityCert: "GREENGUARD Gold",
    description:
      "Advanced ergonomic chair with pixelated seat and dynamic back support.",
    thumbnailColor: "oklch(0.35 0.02 240)",
    tags: ["ergonomic", "premium", "task"],
  },
  {
    id: "fm-003",
    name: "Gesture Chair",
    brand: SC,
    category: "Seating",
    style: ["Modern", "Contemporary"],
    dimensions: { widthIn: 27, depthIn: 18, heightIn: 44, weightLbs: 38 },
    priceRangeLow: 1300,
    priceRangeHigh: 1700,
    availableMaterials: [MATERIALS[24]],
    csiCode: "12 51 13",
    leadTimeWeeks: 4,
    sustainabilityCert: "GREENGUARD Gold",
    description:
      "360° arm movement supporting the widest range of postures for mobile devices.",
    thumbnailColor: "oklch(0.42 0.03 240)",
    tags: ["ergonomic", "task", "tech-forward"],
  },
  {
    id: "fm-004",
    name: "Leap V2 Chair",
    brand: SC,
    category: "Seating",
    style: ["Modern"],
    dimensions: { widthIn: 26, depthIn: 17, heightIn: 42, weightLbs: 36 },
    priceRangeLow: 1100,
    priceRangeHigh: 1500,
    availableMaterials: [MATERIALS[24]],
    csiCode: "12 51 13",
    leadTimeWeeks: 4,
    sustainabilityCert: "GREENGUARD",
    description:
      "Natural Glide System follows spinal movement for sustained comfort.",
    thumbnailColor: "oklch(0.5 0.03 240)",
    tags: ["ergonomic", "task"],
  },
  {
    id: "fm-005",
    name: "Freedom Task Chair",
    brand: HS,
    category: "Seating",
    style: ["Modern", "Minimalist"],
    dimensions: { widthIn: 26, depthIn: 17, heightIn: 43, weightLbs: 34 },
    priceRangeLow: 1200,
    priceRangeHigh: 1600,
    availableMaterials: [MATERIALS[27]],
    csiCode: "12 51 13",
    leadTimeWeeks: 4,
    sustainabilityCert: "GREENGUARD",
    description:
      "Auto-adjusting headrest and recline for hands-free ergonomic support.",
    thumbnailColor: "oklch(0.45 0.02 240)",
    tags: ["ergonomic", "headrest"],
  },
  {
    id: "fm-006",
    name: "Mirra 2 Chair",
    brand: HM,
    category: "Seating",
    style: ["Modern"],
    dimensions: { widthIn: 26, depthIn: 17, heightIn: 41, weightLbs: 32 },
    priceRangeLow: 900,
    priceRangeHigh: 1200,
    availableMaterials: [MATERIALS[27]],
    csiCode: "12 51 13",
    leadTimeWeeks: 4,
    sustainabilityCert: "GREENGUARD Gold",
    description:
      "Butterfly back with independent flex zones for micro-movement support.",
    thumbnailColor: "oklch(0.55 0.08 245)",
    tags: ["task", "mesh"],
  },
  {
    id: "fm-007",
    name: "Karman Chair",
    brand: HW,
    category: "Seating",
    style: ["Modern", "Minimalist"],
    dimensions: { widthIn: 26, depthIn: 17, heightIn: 42, weightLbs: 30 },
    priceRangeLow: 1100,
    priceRangeHigh: 1500,
    availableMaterials: [MATERIALS[27]],
    csiCode: "12 51 13",
    leadTimeWeeks: 5,
    description: "Woven core with kinetic recline, ultra-slim profile.",
    thumbnailColor: "oklch(0.6 0.02 240)",
    tags: ["task", "slim"],
  },
  {
    id: "fm-008",
    name: "Fern Chair",
    brand: HM,
    category: "Seating",
    style: ["Biophilic", "Modern"],
    dimensions: { widthIn: 27, depthIn: 17, heightIn: 42, weightLbs: 35 },
    priceRangeLow: 1700,
    priceRangeHigh: 2100,
    availableMaterials: [MATERIALS[26]],
    csiCode: "12 51 13",
    leadTimeWeeks: 5,
    sustainabilityCert: "GREENGUARD Gold",
    description:
      "Frond-inspired back that adapts to every movement with organic aesthetics.",
    thumbnailColor: "oklch(0.45 0.08 145)",
    tags: ["biophilic", "task", "premium"],
  },
  {
    id: "fm-009",
    name: "Cosm Chair",
    brand: HM,
    category: "Seating",
    style: ["Modern", "Contemporary"],
    dimensions: { widthIn: 27, depthIn: 17, heightIn: 41, weightLbs: 28 },
    priceRangeLow: 1300,
    priceRangeHigh: 1600,
    availableMaterials: [MATERIALS[27]],
    csiCode: "12 51 13",
    leadTimeWeeks: 4,
    sustainabilityCert: "GREENGUARD Gold",
    description:
      "Auto-harmonic tilt with suspended back, zero-adjustment design.",
    thumbnailColor: "oklch(0.38 0.04 240)",
    tags: ["task", "auto-adjust"],
  },
  {
    id: "fm-010",
    name: "Reply Chair",
    brand: SC,
    category: "Seating",
    style: ["Modern"],
    dimensions: { widthIn: 26, depthIn: 17, heightIn: 42, weightLbs: 30 },
    priceRangeLow: 900,
    priceRangeHigh: 1200,
    availableMaterials: [MATERIALS[27]],
    csiCode: "12 51 13",
    leadTimeWeeks: 3,
    description: "Mesh back with integrated lumbar for open-plan workspaces.",
    thumbnailColor: "oklch(0.52 0.03 240)",
    tags: ["task", "value"],
  },
  // ── LOUNGE & COLLABORATIVE (15) ───────────────────────────────────────────
  {
    id: "fm-011",
    name: "Eames Lounge Chair & Ottoman",
    brand: HM,
    category: "Lounge",
    style: ["Modern", "Contemporary", "Luxury"],
    dimensions: { widthIn: 33, depthIn: 32, heightIn: 34, weightLbs: 88 },
    priceRangeLow: 5800,
    priceRangeHigh: 7200,
    availableMaterials: [MATERIALS[36]],
    csiCode: "12 51 23",
    leadTimeWeeks: 6,
    sustainabilityCert: "GREENGUARD Gold",
    description:
      "Iconic mid-century lounge in molded plywood shell with leather cushioning.",
    thumbnailColor: "oklch(0.32 0.04 35)",
    tags: ["iconic", "lounge", "executive", "classic"],
  },
  {
    id: "fm-012",
    name: "Brno Flat Bar Chair",
    brand: KN,
    category: "Lounge",
    style: ["Modern", "Industrial"],
    dimensions: { widthIn: 22, depthIn: 20, heightIn: 33, weightLbs: 22 },
    priceRangeLow: 1800,
    priceRangeHigh: 2400,
    availableMaterials: [MATERIALS[37]],
    csiCode: "12 51 23",
    leadTimeWeeks: 5,
    description:
      "Mies van der Rohe designed cantilever side chair with flat bar frame.",
    thumbnailColor: "oklch(0.18 0.01 240)",
    tags: ["bauhaus", "iconic", "dining"],
  },
  {
    id: "fm-013",
    name: "Womb Chair",
    brand: KN,
    category: "Lounge",
    style: ["Contemporary", "Luxury"],
    dimensions: { widthIn: 40, depthIn: 34, heightIn: 36, weightLbs: 55 },
    priceRangeLow: 4800,
    priceRangeHigh: 6000,
    availableMaterials: [MATERIALS[22]],
    csiCode: "12 51 23",
    leadTimeWeeks: 7,
    description: "Eero Saarinen's enveloping fiberglass shell lounge chair.",
    thumbnailColor: "oklch(0.62 0.08 25)",
    tags: ["iconic", "lounge", "boutique", "hotel"],
  },
  {
    id: "fm-014",
    name: "Plex Lounge",
    brand: SC,
    category: "Lounge",
    style: ["Modern", "Contemporary"],
    dimensions: { widthIn: 28, depthIn: 26, heightIn: 32, weightLbs: 35 },
    priceRangeLow: 2400,
    priceRangeHigh: 3200,
    availableMaterials: [MATERIALS[22], MATERIALS[26]],
    csiCode: "12 51 23",
    leadTimeWeeks: 5,
    description:
      "Flexible lounge with weight-activated recline, suitable for collaborative zones.",
    thumbnailColor: "oklch(0.55 0.05 240)",
    tags: ["lounge", "collaborative"],
  },
  {
    id: "fm-015",
    name: "Coalesse Bob Chair",
    brand: SC,
    category: "Lounge",
    style: ["Modern", "Minimalist"],
    dimensions: { widthIn: 27, depthIn: 26, heightIn: 31, weightLbs: 29 },
    priceRangeLow: 2200,
    priceRangeHigh: 3000,
    availableMaterials: [MATERIALS[22]],
    csiCode: "12 51 23",
    leadTimeWeeks: 5,
    description:
      "Clean-lined sled base lounge for open offices and hotel lobbies.",
    thumbnailColor: "oklch(0.7 0.06 240)",
    tags: ["lounge", "hotel-lobby"],
  },
  {
    id: "fm-016",
    name: "Antenna Lounge",
    brand: HM,
    category: "Lounge",
    style: ["Modern", "Contemporary"],
    dimensions: { widthIn: 32, depthIn: 30, heightIn: 34, weightLbs: 40 },
    priceRangeLow: 2800,
    priceRangeHigh: 3600,
    availableMaterials: [MATERIALS[22], MATERIALS[25]],
    csiCode: "12 51 23",
    leadTimeWeeks: 5,
    description:
      "Comfortable lounge with warm wood accents for collaborative common areas.",
    thumbnailColor: "oklch(0.48 0.06 240)",
    tags: ["lounge", "collaborative"],
  },
  {
    id: "fm-017",
    name: "Bassline Sofa",
    brand: HW,
    category: "Lounge",
    style: ["Contemporary", "Hospitality"],
    dimensions: { widthIn: 84, depthIn: 34, heightIn: 32, weightLbs: 120 },
    priceRangeLow: 6000,
    priceRangeHigh: 8000,
    availableMaterials: [MATERIALS[22], MATERIALS[24]],
    csiCode: "12 51 23",
    leadTimeWeeks: 7,
    description:
      "Modular lounge seating system for hotel lobbies and collaborative hubs.",
    thumbnailColor: "oklch(0.3 0.02 240)",
    tags: ["sofa", "hospitality", "modular"],
  },
  {
    id: "fm-018",
    name: "Muuto Outline Sofa",
    brand: WE,
    category: "Lounge",
    style: ["Scandinavian", "Minimalist"],
    dimensions: { widthIn: 80, depthIn: 35, heightIn: 30, weightLbs: 110 },
    priceRangeLow: 3500,
    priceRangeHigh: 5000,
    availableMaterials: [MATERIALS[22], MATERIALS[25]],
    csiCode: "12 51 23",
    leadTimeWeeks: 6,
    description: "Scandinavian sofa with slim silhouette and removable covers.",
    thumbnailColor: "oklch(0.65 0.04 240)",
    tags: ["sofa", "scandinavian"],
  },
  {
    id: "fm-019",
    name: "Nelson Marshmallow Sofa",
    brand: HM,
    category: "Lounge",
    style: ["Contemporary", "Art Deco"],
    dimensions: { widthIn: 52, depthIn: 32, heightIn: 32, weightLbs: 65 },
    priceRangeLow: 7200,
    priceRangeHigh: 9000,
    availableMaterials: [MATERIALS[22], MATERIALS[24]],
    csiCode: "12 51 23",
    leadTimeWeeks: 8,
    sustainabilityCert: "GREENGUARD Gold",
    description:
      "George Nelson's iconic circular cushion sofa, collector-grade statement piece.",
    thumbnailColor: "oklch(0.6 0.18 42)",
    tags: ["iconic", "statement", "lounge"],
  },
  {
    id: "fm-020",
    name: "Halcon Solis Lounge",
    brand: KB,
    category: "Lounge",
    style: ["Hospitality", "Luxury"],
    dimensions: { widthIn: 30, depthIn: 28, heightIn: 33, weightLbs: 42 },
    priceRangeLow: 2600,
    priceRangeHigh: 3400,
    availableMaterials: [MATERIALS[22], MATERIALS[37]],
    csiCode: "12 51 23",
    leadTimeWeeks: 6,
    description:
      "Plush hospitality lounge with integrated USB charging and solid wood base.",
    thumbnailColor: "oklch(0.42 0.06 35)",
    tags: ["hospitality", "tech-integrated"],
  },
  {
    id: "fm-021",
    name: "Keilhauer Scamp",
    brand: KB,
    category: "Lounge",
    style: ["Modern", "Minimalist"],
    dimensions: { widthIn: 26, depthIn: 26, heightIn: 30, weightLbs: 30 },
    priceRangeLow: 1800,
    priceRangeHigh: 2400,
    availableMaterials: [MATERIALS[22]],
    csiCode: "12 51 23",
    leadTimeWeeks: 5,
    description:
      "Compact lounge chair for breakout zones with optional tablet arm.",
    thumbnailColor: "oklch(0.58 0.04 240)",
    tags: ["lounge", "compact"],
  },
  {
    id: "fm-022",
    name: "Allermuir Halia",
    brand: "Allermuir",
    category: "Lounge",
    style: ["Contemporary", "Biophilic"],
    dimensions: { widthIn: 30, depthIn: 29, heightIn: 31, weightLbs: 38 },
    priceRangeLow: 2200,
    priceRangeHigh: 3000,
    availableMaterials: [MATERIALS[22], MATERIALS[25]],
    csiCode: "12 51 23",
    leadTimeWeeks: 5,
    description:
      "Organic-form lounge with wood veneer back and cushioned seat.",
    thumbnailColor: "oklch(0.52 0.08 145)",
    tags: ["biophilic", "lounge"],
  },
  {
    id: "fm-023",
    name: "Vitra Alcove Sofa",
    brand: VT,
    category: "Lounge",
    style: ["Contemporary", "Minimalist"],
    dimensions: { widthIn: 84, depthIn: 54, heightIn: 48, weightLbs: 140 },
    priceRangeLow: 8000,
    priceRangeHigh: 11000,
    availableMaterials: [MATERIALS[22], MATERIALS[25]],
    csiCode: "12 51 23",
    leadTimeWeeks: 8,
    description:
      "High-back alcove sofa creating private islands in open spaces.",
    thumbnailColor: "oklch(0.28 0.02 240)",
    tags: ["privacy", "lounge", "statement"],
  },
  {
    id: "fm-024",
    name: "Muuto Connect Sofa",
    brand: WE,
    category: "Lounge",
    style: ["Scandinavian", "Minimalist"],
    dimensions: { widthIn: 76, depthIn: 33, heightIn: 28, weightLbs: 98 },
    priceRangeLow: 4200,
    priceRangeHigh: 5800,
    availableMaterials: [MATERIALS[22], MATERIALS[25]],
    csiCode: "12 51 23",
    leadTimeWeeks: 6,
    description:
      "Modular sofa system with curved connectors for flexible lounge layouts.",
    thumbnailColor: "oklch(0.7 0.04 240)",
    tags: ["modular", "lounge", "scandinavian"],
  },
  {
    id: "fm-025",
    name: "Vitra Soft Modular",
    brand: VT,
    category: "Lounge",
    style: ["Contemporary", "Luxury"],
    dimensions: { widthIn: 96, depthIn: 40, heightIn: 28, weightLbs: 160 },
    priceRangeLow: 9500,
    priceRangeHigh: 14000,
    availableMaterials: [MATERIALS[22], MATERIALS[24]],
    csiCode: "12 51 23",
    leadTimeWeeks: 10,
    description:
      "Modular lounge with down-feather cushions and cast aluminum feet.",
    thumbnailColor: "oklch(0.35 0.04 240)",
    tags: ["modular", "luxury", "premium"],
  },
  // ── CONFERENCE & MEETING (12) ─────────────────────────────────────────────
  {
    id: "fm-026",
    name: "Saarinen Conference Table",
    brand: KN,
    category: "Conference",
    style: ["Modern", "Contemporary", "Luxury"],
    dimensions: { widthIn: 96, depthIn: 48, heightIn: 29, weightLbs: 260 },
    priceRangeLow: 8000,
    priceRangeHigh: 12000,
    availableMaterials: [MATERIALS[43], MATERIALS[45]],
    csiCode: "12 52 19",
    leadTimeWeeks: 8,
    description:
      "Iconic pedestal conference table in marble, laminate, or wood top options.",
    thumbnailColor: "oklch(0.62 0.02 240)",
    tags: ["iconic", "conference", "boardroom"],
  },
  {
    id: "fm-027",
    name: "Antenna Worksurface Table",
    brand: HM,
    category: "Conference",
    style: ["Modern", "Minimalist"],
    dimensions: { widthIn: 72, depthIn: 36, heightIn: 29, weightLbs: 140 },
    priceRangeLow: 3200,
    priceRangeHigh: 4800,
    availableMaterials: [MATERIALS[0], MATERIALS[1]],
    csiCode: "12 52 19",
    leadTimeWeeks: 5,
    description: "Clean-line conference table with integrated power access.",
    thumbnailColor: "oklch(0.55 0.04 240)",
    tags: ["conference", "integrated-power"],
  },
  {
    id: "fm-028",
    name: "Steelcase Coalesse Bix",
    brand: SC,
    category: "Conference",
    style: ["Modern"],
    dimensions: { widthIn: 48, depthIn: 48, heightIn: 29, weightLbs: 120 },
    priceRangeLow: 2800,
    priceRangeHigh: 4000,
    availableMaterials: [MATERIALS[0]],
    csiCode: "12 52 19",
    leadTimeWeeks: 5,
    description:
      "Round collaborative meeting table with base and integrated connectivity.",
    thumbnailColor: "oklch(0.48 0.04 240)",
    tags: ["round", "collaborative", "conference"],
  },
  {
    id: "fm-029",
    name: "Knoll Propeller Table",
    brand: KN,
    category: "Conference",
    style: ["Modern", "Contemporary"],
    dimensions: { widthIn: 120, depthIn: 48, heightIn: 29, weightLbs: 320 },
    priceRangeLow: 10000,
    priceRangeHigh: 15000,
    availableMaterials: [MATERIALS[1], MATERIALS[43]],
    csiCode: "12 52 19",
    leadTimeWeeks: 8,
    description:
      "Boat-shaped executive conference table with integrated cable access.",
    thumbnailColor: "oklch(0.28 0.04 35)",
    tags: ["executive", "boardroom", "conference"],
  },
  {
    id: "fm-030",
    name: "Vitra Workbay",
    brand: VT,
    category: "Conference",
    style: ["Contemporary", "Industrial"],
    dimensions: { widthIn: 72, depthIn: 36, heightIn: 29, weightLbs: 160 },
    priceRangeLow: 4500,
    priceRangeHigh: 6500,
    availableMaterials: [MATERIALS[0], MATERIALS[3]],
    csiCode: "12 52 19",
    leadTimeWeeks: 7,
    description:
      "Functional conference table with structural frame and wood panel top.",
    thumbnailColor: "oklch(0.5 0.05 240)",
    tags: ["conference", "industrial"],
  },
  {
    id: "fm-031",
    name: "Allsteel Define Table",
    brand: HW,
    category: "Conference",
    style: ["Modern"],
    dimensions: { widthIn: 84, depthIn: 42, heightIn: 29, weightLbs: 180 },
    priceRangeLow: 3500,
    priceRangeHigh: 5000,
    availableMaterials: [MATERIALS[0], MATERIALS[57]],
    csiCode: "12 52 19",
    leadTimeWeeks: 5,
    description:
      "Clean conference table with integrated power and multiple top options.",
    thumbnailColor: "oklch(0.52 0.03 240)",
    tags: ["conference"],
  },
  {
    id: "fm-032",
    name: "OFS Brands Hug Table",
    brand: KB,
    category: "Conference",
    style: ["Contemporary", "Hospitality"],
    dimensions: { widthIn: 54, depthIn: 54, heightIn: 29, weightLbs: 130 },
    priceRangeLow: 4000,
    priceRangeHigh: 6000,
    availableMaterials: [MATERIALS[0], MATERIALS[44]],
    csiCode: "12 52 19",
    leadTimeWeeks: 6,
    description:
      "Unique kidney-shaped conference table for inclusive collaboration.",
    thumbnailColor: "oklch(0.45 0.06 35)",
    tags: ["hospitality", "conference", "unique"],
  },
  {
    id: "fm-033",
    name: "Knoll Florence Table",
    brand: KN,
    category: "Conference",
    style: ["Minimalist", "Modern"],
    dimensions: { widthIn: 72, depthIn: 36, heightIn: 29, weightLbs: 145 },
    priceRangeLow: 5500,
    priceRangeHigh: 8000,
    availableMaterials: [MATERIALS[1], MATERIALS[43]],
    csiCode: "12 52 19",
    leadTimeWeeks: 7,
    description:
      "Florence Knoll precision-crafted conference table, available in 30+ configurations.",
    thumbnailColor: "oklch(0.35 0.04 240)",
    tags: ["classic", "executive", "conference"],
  },
  {
    id: "fm-034",
    name: "Teknion Dash Table",
    brand: TK,
    category: "Conference",
    style: ["Modern", "Minimalist"],
    dimensions: { widthIn: 60, depthIn: 30, heightIn: 29, weightLbs: 110 },
    priceRangeLow: 2200,
    priceRangeHigh: 3200,
    availableMaterials: [MATERIALS[0], MATERIALS[57]],
    csiCode: "12 52 19",
    leadTimeWeeks: 4,
    description: "Lightweight training/meeting table for multipurpose rooms.",
    thumbnailColor: "oklch(0.6 0.04 240)",
    tags: ["training", "multipurpose"],
  },
  {
    id: "fm-035",
    name: "Steelcase Await",
    brand: SC,
    category: "Conference",
    style: ["Contemporary"],
    dimensions: { widthIn: 48, depthIn: 48, heightIn: 29, weightLbs: 115 },
    priceRangeLow: 2600,
    priceRangeHigh: 3800,
    availableMaterials: [MATERIALS[0]],
    csiCode: "12 52 19",
    leadTimeWeeks: 5,
    description:
      "Intuitive round meeting table enabling spontaneous, inclusive discussion.",
    thumbnailColor: "oklch(0.55 0.04 240)",
    tags: ["round", "meeting"],
  },
  {
    id: "fm-036",
    name: "Allermuir Arc Table",
    brand: "Allermuir",
    category: "Conference",
    style: ["Contemporary", "Biophilic"],
    dimensions: { widthIn: 66, depthIn: 33, heightIn: 29, weightLbs: 130 },
    priceRangeLow: 3200,
    priceRangeHigh: 4600,
    availableMaterials: [MATERIALS[0], MATERIALS[3]],
    csiCode: "12 52 19",
    leadTimeWeeks: 5,
    description: "Arcuate conference table with solid wood leg detail.",
    thumbnailColor: "oklch(0.5 0.07 145)",
    tags: ["biophilic", "conference"],
  },
  {
    id: "fm-037",
    name: "Humanscale Renew Sit-Stand",
    brand: HS,
    category: "Conference",
    style: ["Modern", "Minimalist"],
    dimensions: { widthIn: 60, depthIn: 30, heightIn: 48, weightLbs: 95 },
    priceRangeLow: 2400,
    priceRangeHigh: 3400,
    availableMaterials: [MATERIALS[0]],
    csiCode: "12 52 19",
    leadTimeWeeks: 4,
    description:
      "Electric height-adjustable conference table for standup meetings.",
    thumbnailColor: "oklch(0.42 0.04 240)",
    tags: ["standing", "adjustable", "conference"],
  },
  // ── DESKING SYSTEMS (12) ─────────────────────────────────────────────────
  {
    id: "fm-038",
    name: "Antenna Workspaces",
    brand: HM,
    category: "Desking",
    style: ["Modern", "Contemporary"],
    dimensions: { widthIn: 60, depthIn: 30, heightIn: 29, weightLbs: 90 },
    priceRangeLow: 1800,
    priceRangeHigh: 2800,
    availableMaterials: [MATERIALS[0], MATERIALS[57]],
    csiCode: "12 51 33",
    leadTimeWeeks: 5,
    sustainabilityCert: "GREENGUARD Gold",
    description:
      "Integrated system desk with shared infrastructure for open plan offices.",
    thumbnailColor: "oklch(0.45 0.04 240)",
    tags: ["systems", "open-plan", "desking"],
  },
  {
    id: "fm-039",
    name: "Layout Studio",
    brand: HM,
    category: "Desking",
    style: ["Modern", "Minimalist"],
    dimensions: { widthIn: 72, depthIn: 36, heightIn: 29, weightLbs: 110 },
    priceRangeLow: 2200,
    priceRangeHigh: 3200,
    availableMaterials: [MATERIALS[0], MATERIALS[1]],
    csiCode: "12 51 33",
    leadTimeWeeks: 5,
    sustainabilityCert: "GREENGUARD Gold",
    description:
      "Clean-line workstation with warm material pairings for focused work.",
    thumbnailColor: "oklch(0.5 0.04 240)",
    tags: ["workstation", "focused"],
  },
  {
    id: "fm-040",
    name: "Steelcase Flex Collection",
    brand: SC,
    category: "Desking",
    style: ["Modern", "Contemporary"],
    dimensions: { widthIn: 60, depthIn: 30, heightIn: 29, weightLbs: 85 },
    priceRangeLow: 1600,
    priceRangeHigh: 2400,
    availableMaterials: [MATERIALS[0], MATERIALS[57]],
    csiCode: "12 51 33",
    leadTimeWeeks: 4,
    sustainabilityCert: "GREENGUARD",
    description:
      "Reconfigurable desking for agile and activity-based work environments.",
    thumbnailColor: "oklch(0.55 0.04 240)",
    tags: ["agile", "flexible", "desking"],
  },
  {
    id: "fm-041",
    name: "Knoll Dividends Horizon",
    brand: KN,
    category: "Desking",
    style: ["Contemporary"],
    dimensions: { widthIn: 66, depthIn: 30, heightIn: 29, weightLbs: 100 },
    priceRangeLow: 2000,
    priceRangeHigh: 3000,
    availableMaterials: [MATERIALS[0], MATERIALS[57]],
    csiCode: "12 51 33",
    leadTimeWeeks: 5,
    description:
      "Panel-based system with contemporary proportions and flexibility.",
    thumbnailColor: "oklch(0.45 0.03 240)",
    tags: ["systems", "panels"],
  },
  {
    id: "fm-042",
    name: "Haworth Planes",
    brand: HW,
    category: "Desking",
    style: ["Modern", "Minimalist"],
    dimensions: { widthIn: 60, depthIn: 30, heightIn: 29, weightLbs: 88 },
    priceRangeLow: 1700,
    priceRangeHigh: 2500,
    availableMaterials: [MATERIALS[0], MATERIALS[57]],
    csiCode: "12 51 33",
    leadTimeWeeks: 5,
    description:
      "Tile-based panel system offering design freedom with vertical integration.",
    thumbnailColor: "oklch(0.5 0.04 240)",
    tags: ["panels", "tiles"],
  },
  {
    id: "fm-043",
    name: "Teknion District",
    brand: TK,
    category: "Desking",
    style: ["Contemporary", "Modern"],
    dimensions: { widthIn: 60, depthIn: 30, heightIn: 29, weightLbs: 92 },
    priceRangeLow: 1900,
    priceRangeHigh: 2800,
    availableMaterials: [MATERIALS[0], MATERIALS[57]],
    csiCode: "12 51 33",
    leadTimeWeeks: 5,
    description:
      "Panel-integrated system accommodating power, data, and glass panels.",
    thumbnailColor: "oklch(0.48 0.04 240)",
    tags: ["integrated", "systems"],
  },
  {
    id: "fm-044",
    name: "Vitra Joyn Workbench",
    brand: VT,
    category: "Desking",
    style: ["Contemporary", "Minimalist"],
    dimensions: { widthIn: 120, depthIn: 48, heightIn: 29, weightLbs: 180 },
    priceRangeLow: 4000,
    priceRangeHigh: 6000,
    availableMaterials: [MATERIALS[0], MATERIALS[3]],
    csiCode: "12 51 33",
    leadTimeWeeks: 7,
    description:
      "Open bench system by Bouroullec brothers for collective working.",
    thumbnailColor: "oklch(0.55 0.04 240)",
    tags: ["bench", "open", "collaborative"],
  },
  {
    id: "fm-045",
    name: "HM Canvas Office",
    brand: HM,
    category: "Desking",
    style: ["Modern"],
    dimensions: { widthIn: 60, depthIn: 30, heightIn: 29, weightLbs: 95 },
    priceRangeLow: 2000,
    priceRangeHigh: 3000,
    availableMaterials: [MATERIALS[0], MATERIALS[57]],
    csiCode: "12 51 33",
    leadTimeWeeks: 5,
    sustainabilityCert: "GREENGUARD Gold",
    description:
      "Canvas system with mixed-use configurability and material combinations.",
    thumbnailColor: "oklch(0.5 0.04 240)",
    tags: ["systems", "flexible"],
  },
  {
    id: "fm-046",
    name: "Allsteel Terrace",
    brand: HW,
    category: "Desking",
    style: ["Contemporary"],
    dimensions: { widthIn: 60, depthIn: 30, heightIn: 29, weightLbs: 90 },
    priceRangeLow: 1500,
    priceRangeHigh: 2200,
    availableMaterials: [MATERIALS[0], MATERIALS[57]],
    csiCode: "12 51 33",
    leadTimeWeeks: 4,
    description: "Value open-plan benching with integrated wire management.",
    thumbnailColor: "oklch(0.55 0.03 240)",
    tags: ["value", "benching", "open-plan"],
  },
  {
    id: "fm-047",
    name: "Steelcase Series 7 Desk",
    brand: SC,
    category: "Desking",
    style: ["Modern"],
    dimensions: { widthIn: 66, depthIn: 30, heightIn: 29, weightLbs: 100 },
    priceRangeLow: 1800,
    priceRangeHigh: 2600,
    availableMaterials: [MATERIALS[0], MATERIALS[57]],
    csiCode: "12 51 33",
    leadTimeWeeks: 4,
    description: "Height-adjustable sit-stand desk with quiet-drive motor.",
    thumbnailColor: "oklch(0.52 0.04 240)",
    tags: ["sit-stand", "adjustable"],
  },
  {
    id: "fm-048",
    name: "Knoll Reff Profiles",
    brand: KN,
    category: "Desking",
    style: ["Contemporary", "Luxury"],
    dimensions: { widthIn: 72, depthIn: 36, heightIn: 29, weightLbs: 150 },
    priceRangeLow: 3500,
    priceRangeHigh: 5500,
    availableMaterials: [MATERIALS[1], MATERIALS[43]],
    csiCode: "12 51 33",
    leadTimeWeeks: 7,
    description:
      "Executive wood-veneer desking with waterfall edge and integrated storage.",
    thumbnailColor: "oklch(0.35 0.05 35)",
    tags: ["executive", "wood", "luxury"],
  },
  {
    id: "fm-049",
    name: "Teknion Optos Desk",
    brand: TK,
    category: "Desking",
    style: ["Modern", "Minimalist"],
    dimensions: { widthIn: 60, depthIn: 30, heightIn: 29, weightLbs: 85 },
    priceRangeLow: 1600,
    priceRangeHigh: 2400,
    availableMaterials: [MATERIALS[0], MATERIALS[57]],
    csiCode: "12 51 33",
    leadTimeWeeks: 4,
    description:
      "Minimal frame-and-panel desk system with natural wood options.",
    thumbnailColor: "oklch(0.5 0.04 240)",
    tags: ["minimal", "desking"],
  },
  // ── STORAGE (10) ─────────────────────────────────────────────────────────
  {
    id: "fm-050",
    name: "Meridian Lateral File",
    brand: HM,
    category: "Storage",
    style: ["Modern", "Contemporary"],
    dimensions: { widthIn: 36, depthIn: 20, heightIn: 30, weightLbs: 120 },
    priceRangeLow: 1200,
    priceRangeHigh: 1600,
    availableMaterials: [MATERIALS[12]],
    csiCode: "12 51 43",
    leadTimeWeeks: 4,
    sustainabilityCert: "GREENGUARD Gold",
    description:
      "Steel lateral file with counterweight mechanism and removable tops.",
    thumbnailColor: "oklch(0.45 0.04 240)",
    tags: ["storage", "filing"],
  },
  {
    id: "fm-051",
    name: "Knoll Open-Back Bookcase",
    brand: KN,
    category: "Storage",
    style: ["Modern", "Minimalist"],
    dimensions: { widthIn: 36, depthIn: 12, heightIn: 72, weightLbs: 95 },
    priceRangeLow: 2400,
    priceRangeHigh: 3200,
    availableMaterials: [MATERIALS[0], MATERIALS[57]],
    csiCode: "12 51 43",
    leadTimeWeeks: 6,
    description:
      "Open shelving unit with optional back panel and laminate or wood tops.",
    thumbnailColor: "oklch(0.55 0.04 240)",
    tags: ["shelving", "open"],
  },
  {
    id: "fm-052",
    name: "Steelcase Flex Caddy",
    brand: SC,
    category: "Storage",
    style: ["Modern"],
    dimensions: { widthIn: 18, depthIn: 18, heightIn: 24, weightLbs: 35 },
    priceRangeLow: 600,
    priceRangeHigh: 900,
    availableMaterials: [MATERIALS[12]],
    csiCode: "12 51 43",
    leadTimeWeeks: 3,
    description:
      "Mobile personal caddy for agile, activity-based work settings.",
    thumbnailColor: "oklch(0.6 0.04 240)",
    tags: ["mobile", "personal", "storage"],
  },
  {
    id: "fm-053",
    name: "Vitra Cyl Container",
    brand: VT,
    category: "Storage",
    style: ["Contemporary", "Minimalist"],
    dimensions: { widthIn: 24, depthIn: 18, heightIn: 18, weightLbs: 50 },
    priceRangeLow: 1800,
    priceRangeHigh: 2400,
    availableMaterials: [MATERIALS[0], MATERIALS[12]],
    csiCode: "12 51 43",
    leadTimeWeeks: 6,
    description: "Cylindrical pedestal storage with oak top and steel frame.",
    thumbnailColor: "oklch(0.5 0.05 240)",
    tags: ["pedestal", "storage"],
  },
  {
    id: "fm-054",
    name: "Haworth Planes Wall Unit",
    brand: HW,
    category: "Storage",
    style: ["Contemporary", "Modern"],
    dimensions: { widthIn: 48, depthIn: 18, heightIn: 60, weightLbs: 150 },
    priceRangeLow: 3000,
    priceRangeHigh: 4500,
    availableMaterials: [MATERIALS[0], MATERIALS[57]],
    csiCode: "12 51 43",
    leadTimeWeeks: 6,
    description: "Full-height storage tower integrating with Planes system.",
    thumbnailColor: "oklch(0.48 0.04 240)",
    tags: ["wall-unit", "storage"],
  },
  {
    id: "fm-055",
    name: "RH Contract Bookcase",
    brand: RH,
    category: "Storage",
    style: ["Luxury", "Contemporary"],
    dimensions: { widthIn: 42, depthIn: 14, heightIn: 80, weightLbs: 180 },
    priceRangeLow: 4500,
    priceRangeHigh: 7000,
    availableMaterials: [MATERIALS[1], MATERIALS[7]],
    csiCode: "12 51 43",
    leadTimeWeeks: 8,
    description:
      "Solid wood bookcase with antiqued hardware for executive and hospitality spaces.",
    thumbnailColor: "oklch(0.35 0.06 35)",
    tags: ["luxury", "wood", "bookcase"],
  },
  {
    id: "fm-056",
    name: "Teknion Zones Storage",
    brand: TK,
    category: "Storage",
    style: ["Modern"],
    dimensions: { widthIn: 36, depthIn: 18, heightIn: 42, weightLbs: 100 },
    priceRangeLow: 1800,
    priceRangeHigh: 2600,
    availableMaterials: [MATERIALS[0], MATERIALS[57]],
    csiCode: "12 51 43",
    leadTimeWeeks: 5,
    description: "Modular zoning storage integrating with Zones office system.",
    thumbnailColor: "oklch(0.5 0.04 240)",
    tags: ["modular", "storage"],
  },
  {
    id: "fm-057",
    name: "HM OE1 Storage",
    brand: HM,
    category: "Storage",
    style: ["Modern", "Minimalist"],
    dimensions: { widthIn: 24, depthIn: 18, heightIn: 36, weightLbs: 80 },
    priceRangeLow: 1400,
    priceRangeHigh: 2000,
    availableMaterials: [MATERIALS[0], MATERIALS[12]],
    csiCode: "12 51 43",
    leadTimeWeeks: 4,
    sustainabilityCert: "GREENGUARD Gold",
    description:
      "Versatile OE1 ecosystem storage for distributed team environments.",
    thumbnailColor: "oklch(0.52 0.04 240)",
    tags: ["ecosystem", "storage"],
  },
  {
    id: "fm-058",
    name: "Steelcase Answer Storage",
    brand: SC,
    category: "Storage",
    style: ["Contemporary"],
    dimensions: { widthIn: 36, depthIn: 20, heightIn: 28, weightLbs: 110 },
    priceRangeLow: 1100,
    priceRangeHigh: 1600,
    availableMaterials: [MATERIALS[12]],
    csiCode: "12 51 43",
    leadTimeWeeks: 4,
    sustainabilityCert: "GREENGUARD",
    description: "Overhead storage bin integrated with Answer panel system.",
    thumbnailColor: "oklch(0.55 0.03 240)",
    tags: ["overhead", "panels", "storage"],
  },
  {
    id: "fm-059",
    name: "RH Modular Media Console",
    brand: RH,
    category: "Casegoods",
    style: ["Luxury", "Contemporary"],
    dimensions: { widthIn: 84, depthIn: 18, heightIn: 24, weightLbs: 200 },
    priceRangeLow: 5800,
    priceRangeHigh: 9000,
    availableMaterials: [MATERIALS[1], MATERIALS[7]],
    csiCode: "12 32 00",
    leadTimeWeeks: 10,
    description:
      "Solid mahogany media console with hand-forged hardware for hospitality suites.",
    thumbnailColor: "oklch(0.28 0.06 35)",
    tags: ["hospitality", "luxury", "casegoods"],
  },
  // ── HOSPITALITY & CASEGOODS (15) ──────────────────────────────────────────
  {
    id: "fm-060",
    name: "RH Cloud Bed",
    brand: RH,
    category: "Hospitality",
    style: ["Luxury", "Contemporary"],
    dimensions: { widthIn: 64, depthIn: 88, heightIn: 52, weightLbs: 280 },
    priceRangeLow: 4500,
    priceRangeHigh: 7500,
    availableMaterials: [MATERIALS[22], MATERIALS[37]],
    csiCode: "12 32 00",
    leadTimeWeeks: 10,
    description:
      "Upholstered platform bed with deep tufted headboard for boutique hospitality.",
    thumbnailColor: "oklch(0.45 0.04 240)",
    tags: ["hospitality", "bed", "luxury"],
  },
  {
    id: "fm-061",
    name: "KI Audrey Guest Chair",
    brand: KB,
    category: "Seating",
    style: ["Hospitality", "Contemporary"],
    dimensions: { widthIn: 24, depthIn: 24, heightIn: 33, weightLbs: 24 },
    priceRangeLow: 800,
    priceRangeHigh: 1200,
    availableMaterials: [MATERIALS[22], MATERIALS[24]],
    csiCode: "12 51 13",
    leadTimeWeeks: 4,
    description:
      "Soft seating guest chair for hospitality reception and healthcare waiting.",
    thumbnailColor: "oklch(0.55 0.06 240)",
    tags: ["guest", "hospitality", "reception"],
  },
  {
    id: "fm-062",
    name: "Bench Dining Communal",
    brand: WE,
    category: "Hospitality",
    style: ["Industrial", "Scandinavian"],
    dimensions: { widthIn: 60, depthIn: 14, heightIn: 18, weightLbs: 65 },
    priceRangeLow: 900,
    priceRangeHigh: 1400,
    availableMaterials: [MATERIALS[0], MATERIALS[13]],
    csiCode: "12 32 00",
    leadTimeWeeks: 4,
    description:
      "Communal dining bench in solid oak or metal for hotel dining areas.",
    thumbnailColor: "oklch(0.5 0.08 35)",
    tags: ["dining", "communal", "hospitality"],
  },
  {
    id: "fm-063",
    name: "Steelcase Bivi Locker",
    brand: SC,
    category: "Storage",
    style: ["Modern"],
    dimensions: { widthIn: 12, depthIn: 18, heightIn: 60, weightLbs: 55 },
    priceRangeLow: 600,
    priceRangeHigh: 900,
    availableMaterials: [MATERIALS[12], MATERIALS[13]],
    csiCode: "12 51 43",
    leadTimeWeeks: 3,
    description:
      "Personal locker with RFID or combination lock for touchdown workers.",
    thumbnailColor: "oklch(0.48 0.04 240)",
    tags: ["locker", "storage", "personal"],
  },
  {
    id: "fm-064",
    name: "Humanscale Float Table",
    brand: HS,
    category: "Desking",
    style: ["Minimalist", "Modern"],
    dimensions: { widthIn: 60, depthIn: 30, heightIn: 48, weightLbs: 90 },
    priceRangeLow: 2200,
    priceRangeHigh: 3200,
    availableMaterials: [MATERIALS[0], MATERIALS[12]],
    csiCode: "12 51 33",
    leadTimeWeeks: 5,
    description:
      "Counterbalance sit-stand table with single-hand height adjustment.",
    thumbnailColor: "oklch(0.45 0.04 240)",
    tags: ["sit-stand", "counterbalance"],
  },
  {
    id: "fm-065",
    name: "West Elm Greenpoint Desk",
    brand: WE,
    category: "Desking",
    style: ["Industrial", "Contemporary"],
    dimensions: { widthIn: 60, depthIn: 28, heightIn: 30, weightLbs: 95 },
    priceRangeLow: 1400,
    priceRangeHigh: 2000,
    availableMaterials: [MATERIALS[0], MATERIALS[13]],
    csiCode: "12 51 33",
    leadTimeWeeks: 5,
    description:
      "Solid mango wood desk with hairpin metal legs for boutique office spaces.",
    thumbnailColor: "oklch(0.45 0.08 35)",
    tags: ["wood", "industrial", "boutique"],
  },
  {
    id: "fm-066",
    name: "Vitra Eames DSW Chair",
    brand: VT,
    category: "Seating",
    style: ["Modern", "Contemporary"],
    dimensions: { widthIn: 18, depthIn: 19, heightIn: 33, weightLbs: 12 },
    priceRangeLow: 600,
    priceRangeHigh: 800,
    availableMaterials: [],
    csiCode: "12 51 13",
    leadTimeWeeks: 5,
    description:
      "Eames shell chair with Eiffel base in polypropylene, iconic and stackable.",
    thumbnailColor: "oklch(0.7 0.16 42)",
    tags: ["iconic", "stackable", "dining"],
  },
  {
    id: "fm-067",
    name: "Allermuir Summit High Stool",
    brand: "Allermuir",
    category: "Seating",
    style: ["Industrial", "Contemporary"],
    dimensions: { widthIn: 20, depthIn: 20, heightIn: 44, weightLbs: 20 },
    priceRangeLow: 700,
    priceRangeHigh: 1100,
    availableMaterials: [MATERIALS[22], MATERIALS[13]],
    csiCode: "12 51 13",
    leadTimeWeeks: 4,
    description:
      "Bar-height stool with swivel seat and footrest for café and lounge.",
    thumbnailColor: "oklch(0.4 0.04 240)",
    tags: ["stool", "bar", "cafe"],
  },
  {
    id: "fm-068",
    name: "KI Valore Bariatric Chair",
    brand: KB,
    category: "Healthcare",
    style: ["Hospitality"],
    dimensions: { widthIn: 28, depthIn: 25, heightIn: 38, weightLbs: 45 },
    priceRangeLow: 1200,
    priceRangeHigh: 1800,
    availableMaterials: [MATERIALS[39]],
    csiCode: "12 51 13",
    leadTimeWeeks: 5,
    description:
      "Heavy-duty seating for healthcare and hospitality applications up to 600 lbs.",
    thumbnailColor: "oklch(0.55 0.04 240)",
    tags: ["healthcare", "bariatric", "durable"],
  },
  {
    id: "fm-069",
    name: "Vitra Eames Rocker",
    brand: VT,
    category: "Lounge",
    style: ["Modern", "Contemporary"],
    dimensions: { widthIn: 25, depthIn: 27, heightIn: 34, weightLbs: 22 },
    priceRangeLow: 1200,
    priceRangeHigh: 1600,
    availableMaterials: [],
    csiCode: "12 51 23",
    leadTimeWeeks: 5,
    description:
      "Iconic fiberglass rocking chair for residential and boutique commercial spaces.",
    thumbnailColor: "oklch(0.75 0.14 42)",
    tags: ["rocker", "iconic", "boutique"],
  },
  {
    id: "fm-070",
    name: "Allermuir Cava Pedestal",
    brand: "Allermuir",
    category: "Accessories",
    style: ["Contemporary", "Biophilic"],
    dimensions: { widthIn: 16, depthIn: 16, heightIn: 24, weightLbs: 18 },
    priceRangeLow: 800,
    priceRangeHigh: 1200,
    availableMaterials: [MATERIALS[0], MATERIALS[13]],
    csiCode: "12 93 00",
    leadTimeWeeks: 4,
    description:
      "Plant stand with solid wood and metal construction for biophilic interior accents.",
    thumbnailColor: "oklch(0.52 0.07 145)",
    tags: ["biophilic", "plant", "accessory"],
  },
  {
    id: "fm-071",
    name: "RH Cloud Table Lamp",
    brand: RH,
    category: "Lighting",
    style: ["Luxury", "Contemporary"],
    dimensions: { widthIn: 18, depthIn: 18, heightIn: 30, weightLbs: 12 },
    priceRangeLow: 600,
    priceRangeHigh: 1000,
    availableMaterials: [],
    csiCode: "16 50 00",
    leadTimeWeeks: 5,
    description:
      "Blown glass table lamp with linen shade for hospitality side tables.",
    thumbnailColor: "oklch(0.75 0.04 50)",
    tags: ["lighting", "table-lamp", "hospitality"],
  },
  {
    id: "fm-072",
    name: "Vitra Flowerpot Table",
    brand: VT,
    category: "Accessories",
    style: ["Contemporary", "Minimalist"],
    dimensions: { widthIn: 12, depthIn: 12, heightIn: 18, weightLbs: 4 },
    priceRangeLow: 300,
    priceRangeHigh: 500,
    availableMaterials: [],
    csiCode: "12 93 00",
    leadTimeWeeks: 4,
    description:
      "Ceramic and metal flower pot in bold designer colors for desk accessories.",
    thumbnailColor: "oklch(0.68 0.18 200)",
    tags: ["accessory", "decor", "compact"],
  },
  {
    id: "fm-073",
    name: "Muuto Fiber Side Chair",
    brand: WE,
    category: "Seating",
    style: ["Scandinavian", "Minimalist"],
    dimensions: { widthIn: 20, depthIn: 21, heightIn: 31, weightLbs: 10 },
    priceRangeLow: 400,
    priceRangeHigh: 650,
    availableMaterials: [],
    csiCode: "12 51 13",
    leadTimeWeeks: 4,
    sustainabilityCert: "Sustainable Material",
    description:
      "Recycled composite shell chair in Scandinavian form with wood legs.",
    thumbnailColor: "oklch(0.62 0.06 145)",
    tags: ["side", "scandinavian", "sustainable"],
  },
  {
    id: "fm-074",
    name: "West Elm Modern Bench",
    brand: WE,
    category: "Lounge",
    style: ["Minimalist", "Industrial"],
    dimensions: { widthIn: 52, depthIn: 16, heightIn: 18, weightLbs: 50 },
    priceRangeLow: 600,
    priceRangeHigh: 1000,
    availableMaterials: [MATERIALS[0], MATERIALS[13]],
    csiCode: "12 51 23",
    leadTimeWeeks: 4,
    description:
      "Upholstered bench with solid wood and metal frame for reception and hotel corridors.",
    thumbnailColor: "oklch(0.48 0.06 35)",
    tags: ["bench", "reception", "corridor"],
  },
  // ── HEALTHCARE (8) ────────────────────────────────────────────────────────
  {
    id: "fm-075",
    name: "KI Jive Series Chair",
    brand: KB,
    category: "Healthcare",
    style: ["Hospitality", "Contemporary"],
    dimensions: { widthIn: 24, depthIn: 22, heightIn: 35, weightLbs: 28 },
    priceRangeLow: 900,
    priceRangeHigh: 1400,
    availableMaterials: [MATERIALS[39]],
    csiCode: "12 51 13",
    leadTimeWeeks: 4,
    description:
      "Antimicrobial upholstered chair for patient and visitor waiting zones.",
    thumbnailColor: "oklch(0.58 0.06 240)",
    tags: ["healthcare", "antimicrobial", "waiting"],
  },
  {
    id: "fm-076",
    name: "Steelcase Flex Care",
    brand: SC,
    category: "Healthcare",
    style: ["Contemporary"],
    dimensions: { widthIn: 26, depthIn: 24, heightIn: 34, weightLbs: 32 },
    priceRangeLow: 1200,
    priceRangeHigh: 1700,
    availableMaterials: [MATERIALS[39]],
    csiCode: "12 51 13",
    leadTimeWeeks: 4,
    description:
      "Flexible healthcare chair with easy-clean vinyl and clean-under base.",
    thumbnailColor: "oklch(0.55 0.04 240)",
    tags: ["healthcare", "clean"],
  },
  {
    id: "fm-077",
    name: "Herman Miller Nala",
    brand: HM,
    category: "Healthcare",
    style: ["Contemporary"],
    dimensions: { widthIn: 26, depthIn: 25, heightIn: 36, weightLbs: 36 },
    priceRangeLow: 1400,
    priceRangeHigh: 1900,
    availableMaterials: [MATERIALS[22], MATERIALS[39]],
    csiCode: "12 51 13",
    leadTimeWeeks: 5,
    sustainabilityCert: "GREENGUARD",
    description:
      "Healthcare seating for family and visitor accommodation with clean-design aesthetics.",
    thumbnailColor: "oklch(0.5 0.04 240)",
    tags: ["healthcare", "family-seating"],
  },
  {
    id: "fm-078",
    name: "Haworth Very Task",
    brand: HW,
    category: "Healthcare",
    style: ["Contemporary"],
    dimensions: { widthIn: 26, depthIn: 17, heightIn: 42, weightLbs: 32 },
    priceRangeLow: 1100,
    priceRangeHigh: 1500,
    availableMaterials: [MATERIALS[27]],
    csiCode: "12 51 13",
    leadTimeWeeks: 4,
    description:
      "Healthcare-grade task chair with antimicrobial treatment and easy wipe-down.",
    thumbnailColor: "oklch(0.52 0.04 240)",
    tags: ["healthcare", "task", "antimicrobial"],
  },
  {
    id: "fm-079",
    name: "Nurture by Knoll",
    brand: KN,
    category: "Healthcare",
    style: ["Contemporary"],
    dimensions: { widthIn: 28, depthIn: 26, heightIn: 36, weightLbs: 40 },
    priceRangeLow: 1600,
    priceRangeHigh: 2200,
    availableMaterials: [MATERIALS[22], MATERIALS[39]],
    csiCode: "12 51 23",
    leadTimeWeeks: 5,
    description:
      "Nurture collection designed specifically for healthcare environments.",
    thumbnailColor: "oklch(0.55 0.04 240)",
    tags: ["healthcare", "holistic"],
  },
  {
    id: "fm-080",
    name: "Haworth Fern Healthcare",
    brand: HW,
    category: "Healthcare",
    style: ["Contemporary", "Biophilic"],
    dimensions: { widthIn: 27, depthIn: 17, heightIn: 42, weightLbs: 34 },
    priceRangeLow: 1600,
    priceRangeHigh: 2100,
    availableMaterials: [MATERIALS[39]],
    csiCode: "12 51 13",
    leadTimeWeeks: 5,
    description:
      "Natural-inspired task seating for healthcare professional workstations.",
    thumbnailColor: "oklch(0.5 0.07 145)",
    tags: ["healthcare", "biophilic"],
  },
  {
    id: "fm-081",
    name: "KI Corsa Mobile Table",
    brand: KB,
    category: "Healthcare",
    style: ["Contemporary"],
    dimensions: { widthIn: 30, depthIn: 18, heightIn: 32, weightLbs: 28 },
    priceRangeLow: 700,
    priceRangeHigh: 1100,
    availableMaterials: [MATERIALS[57]],
    csiCode: "12 52 00",
    leadTimeWeeks: 3,
    description:
      "Mobile overbed table for patient rooms and healthcare waiting areas.",
    thumbnailColor: "oklch(0.62 0.04 240)",
    tags: ["mobile", "healthcare", "overbed"],
  },
  {
    id: "fm-082",
    name: "Steelcase 423 Sleep Chair",
    brand: SC,
    category: "Healthcare",
    style: ["Contemporary"],
    dimensions: { widthIn: 28, depthIn: 30, heightIn: 37, weightLbs: 60 },
    priceRangeLow: 2200,
    priceRangeHigh: 3200,
    availableMaterials: [MATERIALS[39]],
    csiCode: "12 51 23",
    leadTimeWeeks: 6,
    description:
      "Reclining sleep chair for family members in patient rooms, full recline position.",
    thumbnailColor: "oklch(0.5 0.04 240)",
    tags: ["healthcare", "recliner", "family"],
  },
  // ── OUTDOOR (8) ────────────────────────────────────────────────────────────
  {
    id: "fm-083",
    name: "West Elm Portside Dining Set",
    brand: WE,
    category: "Outdoor",
    style: ["Contemporary", "Industrial"],
    dimensions: { widthIn: 72, depthIn: 36, heightIn: 29, weightLbs: 220 },
    priceRangeLow: 2800,
    priceRangeHigh: 4200,
    availableMaterials: [MATERIALS[7], MATERIALS[19]],
    csiCode: "12 90 00",
    leadTimeWeeks: 6,
    description: "Solid teak outdoor dining set with powder-coated steel legs.",
    thumbnailColor: "oklch(0.5 0.09 35)",
    tags: ["outdoor", "teak", "dining"],
  },
  {
    id: "fm-084",
    name: "RH Aegean Teak Chair",
    brand: RH,
    category: "Outdoor",
    style: ["Luxury", "Contemporary"],
    dimensions: { widthIn: 26, depthIn: 28, heightIn: 33, weightLbs: 40 },
    priceRangeLow: 1400,
    priceRangeHigh: 2200,
    availableMaterials: [MATERIALS[31]],
    csiCode: "12 90 00",
    leadTimeWeeks: 8,
    description:
      "Solid teak outdoor armchair with Sunbrella cushions for hotel terraces.",
    thumbnailColor: "oklch(0.5 0.09 35)",
    tags: ["outdoor", "teak", "luxury"],
  },
  {
    id: "fm-085",
    name: "Vitra Eames Plastic Chair",
    brand: VT,
    category: "Outdoor",
    style: ["Modern", "Contemporary"],
    dimensions: { widthIn: 21, depthIn: 22, heightIn: 34, weightLbs: 10 },
    priceRangeLow: 450,
    priceRangeHigh: 650,
    availableMaterials: [],
    csiCode: "12 90 00",
    leadTimeWeeks: 4,
    description:
      "UV-stabilized Eames plastic side chair for outdoor café and terrace settings.",
    thumbnailColor: "oklch(0.68 0.14 25)",
    tags: ["outdoor", "iconic", "cafe"],
  },
  {
    id: "fm-086",
    name: "West Elm Woven Lounge",
    brand: WE,
    category: "Outdoor",
    style: ["Contemporary", "Biophilic"],
    dimensions: { widthIn: 30, depthIn: 30, heightIn: 32, weightLbs: 28 },
    priceRangeLow: 1000,
    priceRangeHigh: 1600,
    availableMaterials: [MATERIALS[31]],
    csiCode: "12 90 00",
    leadTimeWeeks: 5,
    description:
      "All-weather woven lounge chair with waterproof cushions for pool deck.",
    thumbnailColor: "oklch(0.55 0.07 50)",
    tags: ["outdoor", "pool", "woven"],
  },
  {
    id: "fm-087",
    name: "Allermuir Kira Outdoor",
    brand: "Allermuir",
    category: "Outdoor",
    style: ["Contemporary", "Industrial"],
    dimensions: { widthIn: 22, depthIn: 21, heightIn: 32, weightLbs: 18 },
    priceRangeLow: 800,
    priceRangeHigh: 1200,
    availableMaterials: [MATERIALS[19]],
    csiCode: "12 90 00",
    leadTimeWeeks: 5,
    description:
      "Powder-coated aluminum side chair for outdoor dining and hospitality terraces.",
    thumbnailColor: "oklch(0.45 0.04 240)",
    tags: ["outdoor", "aluminum", "terrace"],
  },
  {
    id: "fm-088",
    name: "RH Aegean Bar Cart",
    brand: RH,
    category: "Hospitality",
    style: ["Luxury", "Art Deco"],
    dimensions: { widthIn: 36, depthIn: 20, heightIn: 40, weightLbs: 55 },
    priceRangeLow: 1800,
    priceRangeHigh: 2800,
    availableMaterials: [MATERIALS[15], MATERIALS[7]],
    csiCode: "12 93 00",
    leadTimeWeeks: 7,
    description:
      "Brass and teak bar cart with glass shelves for hospitality suite service.",
    thumbnailColor: "oklch(0.55 0.14 50)",
    tags: ["hospitality", "bar", "luxury"],
  },
  {
    id: "fm-089",
    name: "KI Strive Outdoor",
    brand: KB,
    category: "Outdoor",
    style: ["Contemporary"],
    dimensions: { widthIn: 22, depthIn: 20, heightIn: 34, weightLbs: 22 },
    priceRangeLow: 600,
    priceRangeHigh: 950,
    availableMaterials: [MATERIALS[19]],
    csiCode: "12 90 00",
    leadTimeWeeks: 4,
    description:
      "Powder-coated steel side chair for commercial outdoor hospitality zones.",
    thumbnailColor: "oklch(0.52 0.04 240)",
    tags: ["outdoor", "commercial"],
  },
  {
    id: "fm-090",
    name: "West Elm Portside Bench",
    brand: WE,
    category: "Outdoor",
    style: ["Industrial", "Contemporary"],
    dimensions: { widthIn: 60, depthIn: 14, heightIn: 18, weightLbs: 55 },
    priceRangeLow: 1100,
    priceRangeHigh: 1600,
    availableMaterials: [MATERIALS[7], MATERIALS[13]],
    csiCode: "12 90 00",
    leadTimeWeeks: 5,
    description: "Solid mango wood outdoor bench with black steel legs.",
    thumbnailColor: "oklch(0.48 0.08 35)",
    tags: ["outdoor", "bench", "entry"],
  },
  // ── LIGHTING (10 additional models) ──────────────────────────────────────
  {
    id: "fm-091",
    name: "Flos Arco Floor Lamp",
    brand: RH,
    category: "Lighting",
    style: ["Modern", "Minimalist"],
    dimensions: { widthIn: 12, depthIn: 12, heightIn: 96, weightLbs: 60 },
    priceRangeLow: 2400,
    priceRangeHigh: 3400,
    availableMaterials: [],
    csiCode: "16 50 00",
    leadTimeWeeks: 6,
    description:
      "Iconic arc floor lamp with marble base and polished aluminum shade.",
    thumbnailColor: "oklch(0.72 0.04 240)",
    tags: ["lighting", "floor", "iconic"],
  },
  {
    id: "fm-092",
    name: "Muuto E27 Pendant",
    brand: WE,
    category: "Lighting",
    style: ["Scandinavian", "Minimalist"],
    dimensions: { widthIn: 10, depthIn: 10, heightIn: 10, weightLbs: 2 },
    priceRangeLow: 200,
    priceRangeHigh: 380,
    availableMaterials: [],
    csiCode: "16 50 00",
    leadTimeWeeks: 3,
    description:
      "Simple porcelain pendant in bold colors, minimal and versatile.",
    thumbnailColor: "oklch(0.68 0.14 200)",
    tags: ["lighting", "pendant", "scandinavian"],
  },
  {
    id: "fm-093",
    name: "RH Linear Chandelier",
    brand: RH,
    category: "Lighting",
    style: ["Luxury", "Art Deco"],
    dimensions: { widthIn: 48, depthIn: 8, heightIn: 6, weightLbs: 25 },
    priceRangeLow: 3200,
    priceRangeHigh: 5500,
    availableMaterials: [],
    csiCode: "16 50 00",
    leadTimeWeeks: 8,
    description:
      "Brass linear chandelier with hand-blown glass globes for hospitality dining.",
    thumbnailColor: "oklch(0.65 0.12 50)",
    tags: ["chandelier", "hospitality", "brass"],
  },
  {
    id: "fm-094",
    name: "Humanscale Diffrient Task Light",
    brand: HS,
    category: "Lighting",
    style: ["Modern", "Minimalist"],
    dimensions: { widthIn: 18, depthIn: 8, heightIn: 18, weightLbs: 4 },
    priceRangeLow: 500,
    priceRangeHigh: 800,
    availableMaterials: [],
    csiCode: "16 50 00",
    leadTimeWeeks: 4,
    description:
      "LED task light with patented auto-adjust technology for zero glare.",
    thumbnailColor: "oklch(0.45 0.04 240)",
    tags: ["task", "led", "ergonomic"],
  },
  {
    id: "fm-095",
    name: "Vitra Akari Lantern",
    brand: VT,
    category: "Lighting",
    style: ["Contemporary", "Biophilic"],
    dimensions: { widthIn: 14, depthIn: 14, heightIn: 20, weightLbs: 2 },
    priceRangeLow: 400,
    priceRangeHigh: 700,
    availableMaterials: [],
    csiCode: "16 50 00",
    leadTimeWeeks: 5,
    description:
      "Isamu Noguchi washi paper lantern for ambient soft glow in lounge zones.",
    thumbnailColor: "oklch(0.9 0.04 50)",
    tags: ["lantern", "ambient", "biophilic"],
  },
  {
    id: "fm-096",
    name: "Hay Matin Table Lamp",
    brand: WE,
    category: "Lighting",
    style: ["Scandinavian", "Contemporary"],
    dimensions: { widthIn: 10, depthIn: 10, heightIn: 22, weightLbs: 3 },
    priceRangeLow: 280,
    priceRangeHigh: 420,
    availableMaterials: [],
    csiCode: "16 50 00",
    leadTimeWeeks: 4,
    description:
      "Steel wire table lamp with round linen shade for desk and nightstand.",
    thumbnailColor: "oklch(0.68 0.06 50)",
    tags: ["table", "linen", "lighting"],
  },
  {
    id: "fm-097",
    name: "Steelcase Soto II Task",
    brand: SC,
    category: "Lighting",
    style: ["Modern", "Contemporary"],
    dimensions: { widthIn: 24, depthIn: 6, heightIn: 20, weightLbs: 5 },
    priceRangeLow: 450,
    priceRangeHigh: 680,
    availableMaterials: [],
    csiCode: "16 50 00",
    leadTimeWeeks: 4,
    description:
      "LED task light with daylight sensor and personal dimming for workstations.",
    thumbnailColor: "oklch(0.55 0.04 240)",
    tags: ["task", "sensor", "led"],
  },
  {
    id: "fm-098",
    name: "West Elm Sculptural Glass Pendant",
    brand: WE,
    category: "Lighting",
    style: ["Contemporary", "Art Deco"],
    dimensions: { widthIn: 8, depthIn: 8, heightIn: 14, weightLbs: 3 },
    priceRangeLow: 180,
    priceRangeHigh: 320,
    availableMaterials: [],
    csiCode: "16 50 00",
    leadTimeWeeks: 3,
    description:
      "Hand-blown amber glass pendant for café, lobby, and hotel corridor accent lighting.",
    thumbnailColor: "oklch(0.7 0.14 50)",
    tags: ["pendant", "glass", "accent"],
  },
  {
    id: "fm-099",
    name: "Flos Aim Pendant",
    brand: RH,
    category: "Lighting",
    style: ["Industrial", "Minimalist"],
    dimensions: { widthIn: 6, depthIn: 6, heightIn: 12, weightLbs: 2 },
    priceRangeLow: 550,
    priceRangeHigh: 800,
    availableMaterials: [],
    csiCode: "16 50 00",
    leadTimeWeeks: 5,
    description:
      "Adjustable steel pendant light with directional LED for accent dining and work surfaces.",
    thumbnailColor: "oklch(0.5 0.04 240)",
    tags: ["pendant", "adjustable", "industrial"],
  },
  {
    id: "fm-100",
    name: "RH New Traditional Sconce",
    brand: RH,
    category: "Lighting",
    style: ["Luxury", "Art Deco"],
    dimensions: { widthIn: 10, depthIn: 8, heightIn: 20, weightLbs: 6 },
    priceRangeLow: 400,
    priceRangeHigh: 750,
    availableMaterials: [],
    csiCode: "16 50 00",
    leadTimeWeeks: 6,
    description:
      "Antique brass wall sconce with linen shade for hotel corridor and guestroom accent.",
    thumbnailColor: "oklch(0.6 0.12 50)",
    tags: ["sconce", "brass", "hotel"],
  },
  // ── ACCESSORIES (3 bonus) ─────────────────────────────────────────────────
  {
    id: "fm-101",
    name: "Vitra Eames Hang-It-All",
    brand: VT,
    category: "Accessories",
    style: ["Contemporary", "Modern"],
    dimensions: { widthIn: 19, depthIn: 5, heightIn: 7, weightLbs: 3 },
    priceRangeLow: 250,
    priceRangeHigh: 380,
    availableMaterials: [],
    csiCode: "12 93 00",
    leadTimeWeeks: 4,
    description:
      "Colorful wire rack with painted wooden balls for hotel entry and breakrooms.",
    thumbnailColor: "oklch(0.72 0.22 145)",
    tags: ["accessory", "entry", "colorful"],
  },
  {
    id: "fm-102",
    name: "Steelcase Flex Easel",
    brand: SC,
    category: "Accessories",
    style: ["Modern", "Industrial"],
    dimensions: { widthIn: 28, depthIn: 28, heightIn: 80, weightLbs: 25 },
    priceRangeLow: 900,
    priceRangeHigh: 1400,
    availableMaterials: [MATERIALS[12]],
    csiCode: "12 93 43",
    leadTimeWeeks: 3,
    description:
      "Mobile whiteboard easel with magnetic steel surface for agile team spaces.",
    thumbnailColor: "oklch(0.52 0.04 240)",
    tags: ["whiteboard", "mobile", "team"],
  },
  {
    id: "fm-103",
    name: "Herman Miller OE1 Boundary Screen",
    brand: HM,
    category: "Accessories",
    style: ["Modern", "Minimalist"],
    dimensions: { widthIn: 48, depthIn: 2, heightIn: 50, weightLbs: 30 },
    priceRangeLow: 700,
    priceRangeHigh: 1100,
    availableMaterials: [MATERIALS[33]],
    csiCode: "12 25 16",
    leadTimeWeeks: 4,
    sustainabilityCert: "GREENGUARD Gold",
    description:
      "Acoustic boundary screen for open-plan workstations with fabric covering.",
    thumbnailColor: "oklch(0.45 0.06 240)",
    tags: ["acoustic", "privacy", "screen"],
  },
];

// ─── Query helpers ────────────────────────────────────────────────────────────

export function queryFurnitureModels(
  filter: {
    brand?: FurnitureBrand;
    category?: FurnitureCategory;
    keyword?: string;
    priceMax?: number;
  } = {},
): FurnitureModel[] {
  return FURNITURE_MODELS.filter((m) => {
    if (filter.brand && m.brand !== filter.brand) return false;
    if (filter.category && m.category !== filter.category) return false;
    if (filter.priceMax && m.priceRangeLow > filter.priceMax) return false;
    if (filter.keyword) {
      const kw = filter.keyword.toLowerCase();
      if (
        !m.name.toLowerCase().includes(kw) &&
        !m.description.toLowerCase().includes(kw) &&
        !m.tags.some((t) => t.includes(kw))
      )
        return false;
    }
    return true;
  });
}

export function queryMaterials(
  filter: {
    materialType?: MaterialType;
    keyword?: string;
    priceMax?: number;
  } = {},
): MaterialItem[] {
  return MATERIALS.filter((m) => {
    if (filter.materialType && m.materialType !== filter.materialType)
      return false;
    if (filter.priceMax && (m.priceSqFt ?? 0) > filter.priceMax) return false;
    if (filter.keyword) {
      const kw = filter.keyword.toLowerCase();
      if (
        !m.name.toLowerCase().includes(kw) &&
        !m.description.toLowerCase().includes(kw)
      )
        return false;
    }
    return true;
  });
}

export const DESIGN_STYLES = [
  "Modern",
  "Minimalist",
  "Scandinavian",
  "Industrial",
  "Luxury",
  "Transitional",
  "Contemporary",
  "Art Deco",
  "Biophilic",
  "Hospitality",
] as const;

export const FURNITURE_CATEGORIES: FurnitureCategory[] = [
  "Seating",
  "Desking",
  "Storage",
  "Lighting",
  "Casegoods",
  "Lounge",
  "Conference",
  "Outdoor",
  "Hospitality",
  "Healthcare",
  "Accessories",
];

export const FURNITURE_BRANDS: FurnitureBrand[] = [
  "Herman Miller",
  "Knoll",
  "Steelcase",
  "Haworth",
  "Humanscale",
  "Vitra",
  "Restoration Hardware",
  "West Elm Contract",
  "Kimball",
  "National Office",
  "Allermuir",
  "Teknion",
];
